FROM debian:bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
  clang \
  llvm \
  libbpf-dev \
  bpftool \
  make \
  git \
  ca-certificates \
  bash && \
  apt-get clean && rm -rf /var/lib/apt/lists*
