FROM debian:bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    kmod \
    git \
    ca-certificates \
    make \
    bash && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

