name: Build Kernel Modules

on:
  push:
    paths:
      - 'modules/kernel/**'
      - 'ci/kernel/scripts/**'
      - '.github/workflows/build_kernel.yml'
  workflow_dispatch:  # allow manual trigger from UI

jobs:
  build_kmod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Kernel Module (inside gcc-kmod-builder container)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ghcr.io/yonatan-ratner/gcc-kmod-builder:latest \
            sh -c "cd /workspace && ./ci/kernel/scripts/build_kmod.sh"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ github.ref_name }}-${{ github.run_number }}
          path: artifacts/kernel/*.ko
