name: Build Kernel Modules

on:
  push:
    paths:
      - "modules/kernel/**"
      - "ci/kernel/scripts/**"
      - ".github/workflows/build_kernel.yml"

  workflow_dispatch: # allow manual trigger from UI

jobs:
  build_kmod:
    strategy:
      matrix:
        base_image: [ubuntu:22.04]
        kernel_version: [generic]
        include:
          - arch: amd64
            runner: ubuntu-latest
          #- arch: arm64
            #  runner: self-hosted

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code1
        uses: actions/checkout@v3

      - name: Set env vars
        run: |
          echo "GITHUB_USER=${{ github.actor }}" >> $GITHUB_ENV
          echo "ARCH=$(uname -m)" >> $GITHUB_ENV
          echo "SAFE_TAG_OS=$(echo '${{ matrix.base_image }}' | tr ':/' '-' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_TAG=${SAFE_TAG_OS}-${{ matrix.kernel_version }}-${ARCH}" >> $GITHUB_ENV

      - name: Build 'kernel builder' container
        run: |
          ./ci/kernel/docker/build_kernel_docker.sh \
            "${{ matrix.base_image }}" \
            "${{ matrix.kernel_version }}" \
            "$ARCH"

      - name: Build kernel modules inside container
        run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace \
            ghcr.io/$GITHUB_USER/kmod-builder:$IMAGE_TAG \
            bash ci/kernel/scripts/build_kmod.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ matrix.kernel_version }}-${{ matrix.arch }}
          path: artifacts/kernel/*.ko
