name: Build All - Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Nightly full build

jobs:
  build_all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build All Domains
        run: bash ci/scripts/build_modules.sh

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: all-artifacts
          path: artifacts/**

