name: Build eBPF Modules

on:
  push:
    paths:
      - "modules/ebpf/**"
      - "ci/ebpf/scripts/**"
      - ".github/workflows/build_ebpf.yml"

  workflow_dispatch: # allow manual trigger from UI

jobs:
  build_ebpf:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/yonatan-ratner/ebpf-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Mark repo as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build eBPF Modules
        run: bash ci/ebpf/scripts/build_bpf.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ebpf-${{ github.ref_name }}-${{ github.run_number }}
          path: artifacts/kernel/*.ko

