name: Build eBPF Modules

on:
  push:
    paths:
      - 'modules/ebpf/**'
      - 'ci/ebpf/scripts/**'

jobs:
  build_ebpf:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/yonatan-ratner/clang-ebpf-builder:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build eBPF Modules
        run: bash ci/ebpf/scripts/build_bpf.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ebpf-artifacts
          path: artifacts/ebpf/*.o

