name: Build Kernel Modules

on:
  push:
    paths:
      - 'modules/kernel/**'
      - 'ci/kernel/scripts/**'
      - '.github/workflows/build_kernel.yml'

  workflow_dispatch: # allow manual trigger from UI

jobs:
  build_kmod:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/yonatan-ratner/gcc-kmod-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Kernel Module
        run: bash ci/kernel/scripts/build_kmod.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ github.ref_name }}-${{ github.run_number }}
          path: artifacts/kernel/*.ko

